### PR TITLE
Include payment dependency via source files instead of build files

### PR DESCRIPTION
**Pull request by pospi**
Fixes webpack build issues present in this module (#2)
Further work needed pending https://github.com/jessepollak/payment/pull/16

### CODE REVIEW

**Comment by pospi** [comment]
That's the payment update through. This one should be fine to merge now (:

**Comment by shatran** [comment]
Merged. Thanks @pospi!

**Comment by shatran** [comment]
I'll include it in the next version once payment will be upgraded to version 0.0.10

**Comment by jessepollak** [comment]
Updated the npm version to 0.0.10 - thanks!

**Comment by shatran** [comment]
@jessepollak for some reason when i try to run my grunt tasks i now get an error:
"Error: Cannot find module 'coffeeify' from 'card-react/node_modules/payment'"
any idea why?

**Comment by shatran** [comment]
@jessepollak i'm not sure but maybe you need to add 'coffeeify' to the dev dependencies in payment's package.json?

**Comment by pospi** [comment]
Perhaps it is an issue with devDependencies, I'm not sure if npm installs those from child modules. You may need to add `coffeeify` to the devDependencies in `card-react` as well.

**Comment by shatran** [comment]
Done. this will be a part of the release.

**Pull request merged**
