### PR TITLE
Fix: set React as a peerDepencency

### PR DESCRIPTION
**Pull request by joeybaker**
This allows the user to determine which version of react they want to use.

### CODE REVIEW

**Comment by shatran** [comment]
Thanks for that @joeybaker. It's probably the better practice to allow the user to use whatever react version they want :). I will merge it and publish it soon.

**Comment by joeybaker** [comment]
@shatran Thanks for merging, but by setting the minimum react version to 15, you disallow 0.14 users from using this module. Is that intentional? I'm not aware of anything that requires v15 of react for this to work.

**Comment by shatran** [comment]
@joeybaker didn't you say it will allow users to use whatever version they want?

**Comment by joeybaker** [comment]
Ermaigawd. I'm the idiot. I thought I set the peer deps right but must have copy/pasted wrong. So sorry!

Will send a correction soon.

**Pull request merged**
